# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(514, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/SARGIN/Desktop/Project/artificial-intelligence.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        palette = QtGui.QPalette()
        background_image = QtGui.QImage("C:/Users/SARGIN/Desktop/Project/back.jpg").scaled(Dialog.size())
        palette.setBrush(QtGui.QPalette.Window, QtGui.QBrush(background_image))
        Dialog.setPalette(palette)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 520, 331, 61))
        self.pushButton.setStyleSheet("border-image: url(:/button.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 16pt \"Segoe UI Black\";\n"
"background-color: qlineargradient(spread:pad, x1:0.577, y1:0.897727, x2:1, y2:0, stop:0 rgba(1, 19, 51), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "YAPAY ZEKA PROJESİ"))
        self.pushButton.setText(_translate("Dialog", "Duygu Durum Analizi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
